language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install: "pip install -r requirements"
# command to run tests
before_script:
  - pep8 --exclude=migrations --ignore=E501,E225 .
script:
  - nosetests